name: FreeFem AUR package

on: 
  push:
    tags: v/[1-9]+.[0-9]+.[0-9]+
    branches: [master]
  pull_request: {}

jobs:
  create_oci_container:
    name: Build OCI Container
    runs-on: ubuntu-20.04
    env:
      _BUILDAH_STARTED_IN_USERNS : ""
      BUILDAH_ISOLATION: chroot
      TERM: xterm # gh action bug

    steps: 
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt-get -y upgrade
          . /etc/os-release
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
          sudo apt update -y
          sudo apt-get -y upgrade
          sudo apt install -y \
          fuse3 \
          libfuse3-dev \
          libfuse-dev \
          fuse-overlayfs \
          buildah \
          podman
          echo "USERNS ENABLED: "
          sysctl kernel.unprivileged_userns_clone
          podman --version
          # Enable overlayfs in containers
          sudo sed -i -e 's|^#mount_program|mount_program|g' /etc/containers/storage.conf
          
      - name: Build FreeFEM podman container image
        run: |
            podman --version
            ./build_arch_ff_container.sh
