name: build RORPO library

on: 
  push:
    tags: v/[1-9]+.[0-9]+.[0-9]+
    branches: [master]
  pull_request: {}

jobs:
  container:
    name: build (base ubuntu)
    runs-on: ubuntu-20.04

    steps: 
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt update -y
          apt-get -y upgrade
          . /etc/os-release
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
          apt update -y
          apt-get -y upgrade
          apt install -y \
          podman

      - name: Build FreeFEM podman container image
        run: |
          podman --version
          ./build_arch_ff_container.sh
