name: build RORPO library

on: 
  push:
    tags: v/[1-9]+.[0-9]+.[0-9]+
    branches: [master]
  pull_request: {}

jobs:
  container:
    name: build (base ubuntu)
    runs-on: ubuntu-latest
    container: ubuntu:20.10 

    steps: 
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt update -y
          apt install -y \
          buildah \
          podman

      - name: Build FreeFEM podman container image
        run: |
          ls
          ./build_arch_ff_container.sh
